//#line 2 "/opt/ros/hydro/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the mst_navigation package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __mst_navigation__POT_NAV_PARAMSCONFIG_H__
#define __mst_navigation__POT_NAV_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mst_navigation
{
  class Pot_Nav_ParamsConfigStatics;
  
  class Pot_Nav_ParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(Pot_Nav_ParamsConfig &config, const Pot_Nav_ParamsConfig &max, const Pot_Nav_ParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const Pot_Nav_ParamsConfig &config1, const Pot_Nav_ParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, Pot_Nav_ParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const Pot_Nav_ParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Pot_Nav_ParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const Pot_Nav_ParamsConfig &config) const = 0;
      virtual void getValue(const Pot_Nav_ParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T Pot_Nav_ParamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (Pot_Nav_ParamsConfig::* field);

      virtual void clamp(Pot_Nav_ParamsConfig &config, const Pot_Nav_ParamsConfig &max, const Pot_Nav_ParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const Pot_Nav_ParamsConfig &config1, const Pot_Nav_ParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, Pot_Nav_ParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const Pot_Nav_ParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Pot_Nav_ParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const Pot_Nav_ParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const Pot_Nav_ParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, Pot_Nav_ParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, Pot_Nav_ParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<Pot_Nav_ParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(Pot_Nav_ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("robot_x"==(*i)->name){robot_x = boost::any_cast<int>(val);}
        if("robot_y"==(*i)->name){robot_y = boost::any_cast<int>(val);}
        if("robot_filled"==(*i)->name){robot_filled = boost::any_cast<bool>(val);}
        if("search_radius"==(*i)->name){search_radius = boost::any_cast<int>(val);}
        if("search_res"==(*i)->name){search_res = boost::any_cast<int>(val);}
        if("display_rays"==(*i)->name){display_rays = boost::any_cast<bool>(val);}
        if("compas_length"==(*i)->name){compas_length = boost::any_cast<double>(val);}
        if("carrot_on_a_stick"==(*i)->name){carrot_on_a_stick = boost::any_cast<double>(val);}
        if("target_weight_y"==(*i)->name){target_weight_y = boost::any_cast<double>(val);}
        if("target_weight_z"==(*i)->name){target_weight_z = boost::any_cast<double>(val);}
        if("target_y_scale"==(*i)->name){target_y_scale = boost::any_cast<double>(val);}
        if("target_x_exp"==(*i)->name){target_x_exp = boost::any_cast<double>(val);}
        if("target_dist_scale"==(*i)->name){target_dist_scale = boost::any_cast<double>(val);}
        if("dist_scale_x"==(*i)->name){dist_scale_x = boost::any_cast<double>(val);}
        if("dist_scale_y"==(*i)->name){dist_scale_y = boost::any_cast<double>(val);}
        if("twist_scalar_y"==(*i)->name){twist_scalar_y = boost::any_cast<double>(val);}
        if("twist_scalar_z"==(*i)->name){twist_scalar_z = boost::any_cast<double>(val);}
        if("edges_per"==(*i)->name){edges_per = boost::any_cast<double>(val);}
        if("stat_per"==(*i)->name){stat_per = boost::any_cast<double>(val);}
        if("previous_per"==(*i)->name){previous_per = boost::any_cast<double>(val);}
        if("lines_per"==(*i)->name){lines_per = boost::any_cast<double>(val);}
        if("flags_per"==(*i)->name){flags_per = boost::any_cast<double>(val);}
        if("obst_per"==(*i)->name){obst_per = boost::any_cast<double>(val);}
        if("grass_per"==(*i)->name){grass_per = boost::any_cast<double>(val);}
      }
    }

    int robot_x;
int robot_y;
bool robot_filled;
int search_radius;
int search_res;
bool display_rays;
double compas_length;
double carrot_on_a_stick;
double target_weight_y;
double target_weight_z;
double target_y_scale;
double target_x_exp;
double target_dist_scale;
double dist_scale_x;
double dist_scale_y;
double twist_scalar_y;
double twist_scalar_z;
double edges_per;
double stat_per;
double previous_per;
double lines_per;
double flags_per;
double obst_per;
double grass_per;

    bool state;
    std::string name;

    
}groups;



//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int robot_x;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int robot_y;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool robot_filled;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int search_radius;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int search_res;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool display_rays;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double compas_length;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double carrot_on_a_stick;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_weight_y;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_weight_z;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_y_scale;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_x_exp;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_dist_scale;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dist_scale_x;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dist_scale_y;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double twist_scalar_y;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double twist_scalar_z;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double edges_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stat_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double previous_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lines_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double flags_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double obst_per;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double grass_per;
//#line 255 "/opt/ros/hydro/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("Pot_Nav_ParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const Pot_Nav_ParamsConfig &__max__ = __getMax__();
      const Pot_Nav_ParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const Pot_Nav_ParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const Pot_Nav_ParamsConfig &__getDefault__();
    static const Pot_Nav_ParamsConfig &__getMax__();
    static const Pot_Nav_ParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const Pot_Nav_ParamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void Pot_Nav_ParamsConfig::ParamDescription<std::string>::clamp(Pot_Nav_ParamsConfig &config, const Pot_Nav_ParamsConfig &max, const Pot_Nav_ParamsConfig &min) const
  {
    return;
  }

  class Pot_Nav_ParamsConfigStatics
  {
    friend class Pot_Nav_ParamsConfig;
    
    Pot_Nav_ParamsConfigStatics()
    {
Pot_Nav_ParamsConfig::GroupDescription<Pot_Nav_ParamsConfig::DEFAULT, Pot_Nav_ParamsConfig> Default("Default", "", 0, 0, true, &Pot_Nav_ParamsConfig::groups);
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot_x = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot_x = 400;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot_x = 200;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("robot_x", "int", 1, "The height of the robot mask.", "", &Pot_Nav_ParamsConfig::robot_x)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("robot_x", "int", 1, "The height of the robot mask.", "", &Pot_Nav_ParamsConfig::robot_x)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot_y = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot_y = 400;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot_y = 100;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("robot_y", "int", 1, "The width of the robot mask.", "", &Pot_Nav_ParamsConfig::robot_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("robot_y", "int", 1, "The width of the robot mask.", "", &Pot_Nav_ParamsConfig::robot_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot_filled = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot_filled = 1;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot_filled = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<bool>("robot_filled", "bool", 1, "Option to disply the robot mask as a filed box", "", &Pot_Nav_ParamsConfig::robot_filled)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<bool>("robot_filled", "bool", 1, "Option to disply the robot mask as a filed box", "", &Pot_Nav_ParamsConfig::robot_filled)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.search_radius = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.search_radius = 1000;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.search_radius = 100;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("search_radius", "int", 1, "The search radius of potential navigation.", "", &Pot_Nav_ParamsConfig::search_radius)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("search_radius", "int", 1, "The search radius of potential navigation.", "", &Pot_Nav_ParamsConfig::search_radius)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.search_res = 1;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.search_res = 360;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.search_res = 180;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("search_res", "int", 1, "The search  degrees of potential navigation.", "", &Pot_Nav_ParamsConfig::search_res)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<int>("search_res", "int", 1, "The search  degrees of potential navigation.", "", &Pot_Nav_ParamsConfig::search_res)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.display_rays = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.display_rays = 1;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.display_rays = 0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<bool>("display_rays", "bool", 1, "Option to disply rays on debug image", "", &Pot_Nav_ParamsConfig::display_rays)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<bool>("display_rays", "bool", 1, "Option to disply rays on debug image", "", &Pot_Nav_ParamsConfig::display_rays)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.compas_length = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.compas_length = 1000.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.compas_length = 200.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("compas_length", "double", 1, "The length of the target and movement.", "", &Pot_Nav_ParamsConfig::compas_length)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("compas_length", "double", 1, "The length of the target and movement.", "", &Pot_Nav_ParamsConfig::compas_length)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.carrot_on_a_stick = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.carrot_on_a_stick = 10.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.carrot_on_a_stick = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("carrot_on_a_stick", "double", 1, "The forward forcing velocity on robot.", "", &Pot_Nav_ParamsConfig::carrot_on_a_stick)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("carrot_on_a_stick", "double", 1, "The forward forcing velocity on robot.", "", &Pot_Nav_ParamsConfig::carrot_on_a_stick)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_weight_y = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_weight_y = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_weight_y = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_weight_y", "double", 1, "The scalar aplied to the y target component.", "", &Pot_Nav_ParamsConfig::target_weight_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_weight_y", "double", 1, "The scalar aplied to the y target component.", "", &Pot_Nav_ParamsConfig::target_weight_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_weight_z = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_weight_z = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_weight_z = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_weight_z", "double", 1, "The scalar aplied to the z target component.", "", &Pot_Nav_ParamsConfig::target_weight_z)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_weight_z", "double", 1, "The scalar aplied to the z target component.", "", &Pot_Nav_ParamsConfig::target_weight_z)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_y_scale = -100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_y_scale = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_y_scale = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_y_scale", "double", 1, "Persentage of y velocity apiled to x velocity", "", &Pot_Nav_ParamsConfig::target_y_scale)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_y_scale", "double", 1, "Persentage of y velocity apiled to x velocity", "", &Pot_Nav_ParamsConfig::target_y_scale)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_x_exp = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_x_exp = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_x_exp = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_x_exp", "double", 1, "Persentage of y velocity apiled to x velocity", "", &Pot_Nav_ParamsConfig::target_x_exp)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_x_exp", "double", 1, "Persentage of y velocity apiled to x velocity", "", &Pot_Nav_ParamsConfig::target_x_exp)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_dist_scale = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_dist_scale = 1000.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_dist_scale = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_dist_scale", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::target_dist_scale)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("target_dist_scale", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::target_dist_scale)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dist_scale_x = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dist_scale_x = 1000.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dist_scale_x = 200.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("dist_scale_x", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::dist_scale_x)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("dist_scale_x", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::dist_scale_x)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dist_scale_y = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dist_scale_y = 1000.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dist_scale_y = 200.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("dist_scale_y", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::dist_scale_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("dist_scale_y", "double", 1, "Percentage of pixel distace aplied", "", &Pot_Nav_ParamsConfig::dist_scale_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.twist_scalar_y = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.twist_scalar_y = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.twist_scalar_y = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("twist_scalar_y", "double", 1, "The scalar aplied to the y twist values.", "", &Pot_Nav_ParamsConfig::twist_scalar_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("twist_scalar_y", "double", 1, "The scalar aplied to the y twist values.", "", &Pot_Nav_ParamsConfig::twist_scalar_y)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.twist_scalar_z = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.twist_scalar_z = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.twist_scalar_z = 1.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("twist_scalar_z", "double", 1, "The scalar aplied to the z twist values.", "", &Pot_Nav_ParamsConfig::twist_scalar_z)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("twist_scalar_z", "double", 1, "The scalar aplied to the z twist values.", "", &Pot_Nav_ParamsConfig::twist_scalar_z)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.edges_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.edges_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.edges_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("edges_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::edges_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("edges_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::edges_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stat_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stat_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stat_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("stat_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::stat_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("stat_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::stat_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.previous_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.previous_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.previous_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("previous_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::previous_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("previous_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::previous_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lines_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lines_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lines_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("lines_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::lines_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("lines_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::lines_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.flags_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.flags_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.flags_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("flags_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::flags_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("flags_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::flags_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.obst_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.obst_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.obst_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("obst_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::obst_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("obst_per", "double", 1, "The percentage that edges are added at.", "", &Pot_Nav_ParamsConfig::obst_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.grass_per = 0.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.grass_per = 100.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.grass_per = 40.0;
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("grass_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::grass_per)));
//#line 260 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr(new Pot_Nav_ParamsConfig::ParamDescription<double>("grass_per", "double", 1, "The percentage that grass is subtracted at.", "", &Pot_Nav_ParamsConfig::grass_per)));
//#line 231 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 231 "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(Pot_Nav_ParamsConfig::AbstractGroupDescriptionConstPtr(new Pot_Nav_ParamsConfig::GroupDescription<Pot_Nav_ParamsConfig::DEFAULT, Pot_Nav_ParamsConfig>(Default)));
//#line 390 "/opt/ros/hydro/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
    
      for (std::vector<Pot_Nav_ParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<Pot_Nav_ParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    Pot_Nav_ParamsConfig __max__;
    Pot_Nav_ParamsConfig __min__;
    Pot_Nav_ParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const Pot_Nav_ParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static Pot_Nav_ParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &Pot_Nav_ParamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const Pot_Nav_ParamsConfig &Pot_Nav_ParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const Pot_Nav_ParamsConfig &Pot_Nav_ParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const Pot_Nav_ParamsConfig &Pot_Nav_ParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<Pot_Nav_ParamsConfig::AbstractParamDescriptionConstPtr> &Pot_Nav_ParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<Pot_Nav_ParamsConfig::AbstractGroupDescriptionConstPtr> &Pot_Nav_ParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const Pot_Nav_ParamsConfigStatics *Pot_Nav_ParamsConfig::__get_statics__()
  {
    const static Pot_Nav_ParamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = Pot_Nav_ParamsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __POT_NAV_PARAMSRECONFIGURATOR_H__
